In [1]:
import tensorflow as tf

In [2]:
print(f"wersja TENSORFLOW: {tf.__version__}")

wersja TENSORFLOW: 2.10.1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
#normalizacja danych graficznych
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions
#wektor wymików dla kategorii 0-9
#wektor zawiera elementy zwane: logits (log-odds)

array([[ 0.13924073, -0.00465067, 0.22002609, -0.351193 , 0.3100705 ,
 0.7882026 , -0.16813262, 0.14188646, -0.28036046, 0.0765637 ]],
 dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.10003097, 0.086625 , 0.10844739, 0.06125504, 0.11866563,
 0.1914146 , 0.07356038, 0.10029598, 0.06575125, 0.09395377]],
 dtype=float32)

In [7]:
#przygotowanie modelu do treningu
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1],predictions).numpy()

1.6533136

In [9]:
model.compile(
    optimizer='adam',
    loss = loss_fn,
    metrics=['accuracy']
)

In [10]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2914 - accuracy: 0.9150
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1459 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1099 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0896 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0781 - accuracy: 0.9751


In [11]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0806 - accuracy: 0.9760 - 568ms/epoch - 2ms/step


[0.08062448352575302, 0.9760000109672546]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.79142558e-08, 7.91062327e-09, 4.25682010e-05, 4.42627861e-05,
        7.05538232e-12, 3.03502077e-08, 1.06969426e-13, 9.99912739e-01,
        1.41782115e-08, 4.57993309e-07],
       [4.48709160e-11, 2.95674708e-05, 9.99964833e-01, 4.95107906e-06,
        9.15329320e-16, 5.07521122e-07, 1.09578302e-09, 2.34270692e-13,
        5.96656804e-08, 5.14447798e-14],
       [1.44368087e-07, 9.98717785e-01, 8.36691834e-05, 4.69981842e-06,
        4.07856642e-05, 2.58953678e-05, 2.63777019e-06, 9.94101400e-04,
        1.27664622e-04, 2.53065878e-06],
       [9.99962926e-01, 1.43832057e-09, 1.84256714e-05, 4.43215214e-07,
        1.32604479e-08, 8.24033668e-06, 4.31483431e-06, 3.56817600e-06,
        2.01130601e-09, 1.99900933e-06],
       [2.27780720e-06, 6.93622035e-11, 2.78781386e-06, 4.52690685e-08,
        9.98230398e-01, 1.35259370e-07, 8.83734629e-07, 6.54182048e-04,
        9.28826012e-07, 1.10831682e-03]], dtype=float32)>