To jest wstęp do bibliotek niezbędnych do wdrożenia narzędzie związanych z <span style="color:red; font-size:14pt">: **implementacją algorymów AI.**</span>
<br>Podstawy biblioteki NUMPY

In [1]:
import numpy as np

In [2]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [3]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [4]:
ar =np.ones(9)

In [5]:
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.empty(11)

array([6.91589584e-310, 6.91589584e-310, 0.00000000e+000, 4.94065646e-324,
 4.94065646e-324, 0.00000000e+000, 0.00000000e+000, 6.91589196e-310,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [7]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [8]:
tabl = [4,6,7,24,5,88,9,45]
print(type(tabl))
print(type(u))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [10]:
mlista = np.array([34,9,68,99,4,78,35,7,8,24])
mlista

array([34, 9, 68, 99, 4, 78, 35, 7, 8, 24])

In [11]:
type(mlista)

numpy.ndarray

In [12]:
krotka = (4,3,6,3,6,3,7,3,7,3)
kr = np.array(krotka)
kr

array([4, 3, 6, 3, 6, 3, 7, 3, 7, 3])

In [13]:
print(type(kr))

<class 'numpy.ndarray'>


In [16]:
zb = {45,65,7,9,32,56,222,4,67,88,34,34,34}
znp = np.array(zb)
znp

array({32, 65, 34, 67, 4, 7, 9, 45, 56, 88, 222}, dtype=object)

In [15]:
print(type(znp))

<class 'numpy.ndarray'>


In [17]:
nb = [45,600,98,-34,56,-2,45,47,67,989,2,123,-455,0,676]
nnb = np.array(nb)
print(nnb)

[  45  600   98  -34   56   -2   45   47   67  989    2  123 -455    0
  676]


In [18]:
nb.sort()

In [ ]:
nb

In [20]:
nnb.sort()

In [21]:
nnb

array([-455, -34, -2, 0, 2, 45, 45, 47, 56, 67, 98,
 123, 600, 676, 989])

In [22]:
print(nb.sort())

None


In [23]:
print(nnb.sort())

None


In [24]:
a = np.array([1,5,23,8])
b = np.array([7,24,34,75])
c = np.array([22,8])

In [25]:
miasto = ['Tarnów','Lublin','Rzeszów']
stolica = ['Warszawa']

In [26]:
miasto = miasto + stolica
miasto

['Tarnów', 'Lublin', 'Rzeszów', 'Warszawa']

In [30]:
# big = a+b+c
# big
big = np.concatenate((a,b,c))
print(big)

[ 1  5 23  8  7 24 34 75 22  8]


In [31]:
x = np.array([[3,5],[8,65]])
print(x)

[[ 3  5]
 [ 8 65]]


In [34]:
xz = [[3,98],[11,65]]
xz

[[3, 98], [11, 65]]

In [35]:
x[0]

array([3, 5])

In [36]:
xz[0]

[3, 98]

In [37]:
xz[0][1]

98

In [38]:
x[0][1]

5

In [39]:
x[0,1]

5

In [42]:
x = np.array([[11,88],[9,76]])
y = np.array([[34,45],[8,36]])

In [43]:
p1 = np.concatenate((x,y),axis=0)
p1

array([[11, 88],
 [ 9, 76],
 [34, 45],
 [ 8, 36]])

In [44]:
p2 = np.concatenate((x,y),axis=1)
p2

array([[11, 88, 34, 45],
 [ 9, 76, 8, 36]])

In [54]:
prosta = np.arange(48)
prosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [55]:
pp = prosta.reshape(2,2,3,2,2)
pp

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]],



       [[[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]],

         [[32, 33],
          [34, 35]]],


        [[[36, 37],
          [38, 39]],

         [[40, 41],
          [42, 43]],

         [[44, 45],
          [46, 47]]]]])

In [56]:
ar = np.array([1,5,6,2,5,8,9,4,2,4,6,8,9,6,5,8])
ar.shape

(16,)

In [57]:
print(ar[:4])

[1 5 6 2]


In [58]:
print(ar[2:5])

[6 2 5]


In [59]:
print(ar[5:])

[8 9 4 2 4 6 8 9 6 5 8]


In [60]:
print(ar[-2])

5


In [61]:
w = np.array([[1,2,3,4],[98,56,78,24],[11,15,16,13]])
w

array([[ 1, 2, 3, 4],
 [98, 56, 78, 24],
 [11, 15, 16, 13]])

In [62]:
print(w[w<5])

[1 2 3 4]


In [63]:
pc = (w>=5)
print(w[pc])

[98 56 78 24 11 15 16 13]


In [64]:
pv = (w%2==0)
print(w[pv])

[ 2  4 98 56 78 24 16]


In [66]:
c = w[(w>2)&(w<21)]
print(c)

[ 3  4 11 15 16 13]
